export const projects = [
    {
        title: 'Site AirLins Viagens',
        description: "Site intitucional criado para a agência de viagens luso-brasileira Air Lins Viagens. Com uma interface moderna e intuitiva, com efeitos visuais que guiam sua atenção por toda a página.",
        image: '/images/airlinsviagens.png',
        source: 'https://github.com/PauloHPMKT/site-air-lins-viagens',
        visit: 'http://www.airlinsviagens.com',
        id: 0,
    },
    {
        title: 'Projeto BarberShop',
        description: "Projeto de conclusão de modulo de CSS avançado Formação FullstackJavaScript. Consiste na criação de um site onepage com um template do nicho de salões e barbearia.",
        image: '/images/barbershop.png',
        source: 'https://github.com/PauloHPMKT/projetoBarberShop',
        visit: 'https://paulohpmkt.github.io/projetoBarberShop/',
        id: 1,
    },
    {
        title: 'Projeto Gastronomic',
        description: "Projeto criado com estrutura de Sass visando criação de mini-curso utilizando o preprocessador de CSS apresentando uma maneira mais funcional e eficiente de desenvolvimento e estilização.",
        image: '/images/gastronomic.png',
        source: 'https://github.com/PauloHPMKT/gastronmicFoodSite.io',
        visit: 'https://paulohpmkt.github.io/gastronmicFoodSite.io/',
        id: 2,
    },
    {
        title: 'Site Nanda Cakes',
        description: "Site institucional Nanda Cakes & Doces .Consiste na criação de um site para apresentação de produtos do nicho de confeitaria e doceria. Utilizando HTML, CSS e JavaScript puro para criação do layout.",
        image: '/images/nandacakes.png',
        source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
        visit: 'https://project.vipuljha.com/covid/',
        id: 3,
    },
    {
        title: 'My LinkTree',
        description: "Web app, mais conhecida como menu de links. Criado com o propósito de peronalizar o famoso link da Bio no Instagram, trata-se de uma aplicação simples porém muito funcional.",
        image: '/images/mylinktree.png',
        source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
        visit: 'https://project.vipuljha.com/covid/',
        id: 4,
    },
    {
        title: 'Thematic Watch',
        description: "Web app, mais conhecida como menu de links. Criado com o propósito de peronalizar o famoso link da Bio no Instagram, trata-se de uma aplicação simples porém muito funcional.",
        image: '/images/digitalthemewatch.png',
        source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
        visit: 'https://project.vipuljha.com/covid/',
        id: 5,
    },
    {
        title: 'Calculadora IMC React',
        description: "Projeto Calculadora IMC utilizando React JS. Criei esse projeto para iniciar meu aprendizado utilizando a biblioteca, com a finadade de treinar hooks de State e eventos de click.",
        image: '/images/imccalculator.png',
        source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
        visit: 'https://project.vipuljha.com/covid/',
        id: 6,
    },
    {
        title: 'Sujeito Link React',
        description: "Projeto Calculadora IMC utilizando React JS. Criei esse projeto para iniciar meu aprendizado utilizando a biblioteca, com a finadade de treinar hooks de State e eventos de click.",
        image: '/images/sujeitolink.png',
        source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
        visit: 'https://project.vipuljha.com/covid/',
        id: 7,
    },

]